project:
  type: website
  output-dir: docs

website:
  title: "Learning Security Controls - Use-Cases"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - href: access-control.qmd
        text: Access Control

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

execute:
  freeze: auto
